/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/index/demo" |
       "/pages/account/index" |
       "/pages/account/withdraw" |
       "/pages/auth/login" |
       "/pages/category/gallery" |
       "/pages/chat/detail" |
       "/pages/discover/index" |
       "/pages/distributor/index" |
       "/pages/distributor/poster" |
       "/pages/message/index" |
       "/pages/notification/index" |
       "/pages/order/create" |
       "/pages/order/detail" |
       "/pages/order/list" |
       "/pages/order/refund" |
       "/pages/package/list" |
       "/pages/photographer/apply" |
       "/pages/photographer/detail" |
       "/pages/photographer/list" |
       "/pages/photographer/manage" |
       "/pages/portfolio/create" |
       "/pages/portfolio/detail" |
       "/pages/portfolio/manage" |
       "/pages/profile/edit" |
       "/pages/profile/index" |
       "/pages/review/create" |
       "/pages/schedule/manage" |
       "/pages/search/index" |
       "/pages/service/create" |
       "/pages/service/manage";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/discover/index" | "/pages/message/index" | "/pages/profile/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
